name: "Google Drive tools Action - recv"
description: "This action sends a file to Google Drive"
inputs:
  file_id:
    description: "The ID of the file or shared drive."
    required: false
    default: ""
  parent_id:
    description: "The ID of the parent folders in remote"
    required: false
    default: ""
  src_file_name:
    description: "The name of the file in remote. When there are multiple files with the same parent id and the same name, only one of them is received."
    required: false
    default: ""
  dest_file_name:
    description: "The name(path) of the file in local filesystem"
    required: true
    default: ""
  dest_mime_type:
    description: "The MIME type of the file."
    required: false
    default: ""
  remove_bom:
    description: "Remove BOM chars in receiving content"
    required: false
    default: ""
outputs:
  file_id:
    description: "The ID of the file that is sended into Google Drive. Be careful, the ID of the file can also be sensitive data."
runs:
  using: "node20"
  main: "dist/index.mjs"
branding:
  icon: "download-cloud"
  color: "blue"
